<?php
$this->layout('layout/layout', [
    'menu' => 'color',
    'selectedMenu' => 'color',
    'isFetch' => 0
]);
?>

<?php $this->section('main'); ?>
<div class="mains">
    <div class="main-item-color">
        <div>
            <h1>wec 色 彩 规 范</h1>
            <h2 class="text-center p-h-m">主 题 视 觉</h2>
            <ul class="flex flex-main lists">
                <li class="col-xs-6 col-md-4 col-lg-4 space list">
                    <h2>主 色 DONNMANT</h2>
                    <ol class="item wec-main-lists">
                        <li class="meta wec-main-item">
                            <div class="meta-text">
                                <strong class="font-normal">BLUE</strong>
                                <div class="p-t-lg">R 23 G 121 B 186</div>
                                <div>HEX 1779BA</div>
                            </div>
                        </li>
                        <li class="meta wec-main-item">
                            <div class="meta-text">
                                <strong class="font-normal">BLUE</strong>
                                <div class="p-t-lg">R 69 G 148 B 200</div>
                                <div>HEX 4594CB</div>
                            </div>
                        </li>
                        <li class="meta wec-main-item">
                            <div class="meta-text">
                                <strong class="font-normal">BLUE</strong>
                                <div class="p-t-lg">R 162 G 201 B 227</div>
                                <div>HEX A2C9E3</div>
                            </div>
                        </li>
                    </ol>
                </li>

                <li class="col-xs-6 col-md-4 col-lg-4 space list">
                    <h2>文 本 TEXT</h2>
                    <ol class="item wec-text-color-lists">
                        <li class="meta wec-text-color-item">
                            <div class="meta-text">
                                <div>R 34 G 34 B 34</div>
                                <div>HEX 222222</div>
                            </div>
                        </li>
                        <li class="meta wec-text-color-item">
                            <div class="meta-text">
                                <div>R 102 G 102 B 102</div>
                                <div>HEX 666666</div>
                            </div>
                        </li>
                        <li class="meta wec-text-color-item">
                            <div class="meta-text">
                                <div>R 153 G 153 B 153</div>
                                <div>HEX 999</div>
                            </div>
                        </li>
                    </ol>
                </li>

                <li class="col-xs-6 col-md-4 col-lg-4 space list">
                    <h2 class="ellipsis">辅助线 AUXILIARY LINE</h2>
                    <ol class="item wec-auxiliary-color-lists">
                        <li class="meta wec-auxiliary-color-item">
                            <div class="meta-text">
                                <div>R 153 G 153 B 153</div>
                                <div>HEX 999</div>
                            </div>
                        </li>
                        <li class="meta wec-auxiliary-color-item">
                            <div class="meta-text">
                                <div>R 204 G 204 B 204</div>
                                <div>HEX ccc</div>
                            </div>
                        </li>
                        <li class="meta wec-auxiliary-color-item">
                            <div class="meta-text">
                                <div>R 221 G 221 B 221</div>
                                <div>HEX ddd</div>
                            </div>
                        </li>
                    </ol>
                </li>

                <li class="col-xs-6 col-md-4 col-lg-4 space list">
                    <h2 class="ellipsis">背景色 BACKGROUND</h2>
                    <ol class="item wec-background-color-lists">
                        <li class="meta wec-background-color-item">
                            <div class="meta-text">
                                <div>R 233 G 233 B 233</div>
                                <div>HEX E9E9E9</div>
                            </div>
                        </li>
                        <li class="meta wec-background-color-item">
                            <div class="meta-text">
                                <div>R 252 G 252 B 252</div>
                                <div>HEX FCFCFC</div>
                            </div>
                        </li>
                        <li class="meta wec-background-color-item">
                            <div class="meta-text">
                                <div>R 255 G 255 B 255</div>
                                <div>HEX FFFFFF</div>
                            </div>
                        </li>
                    </ol>
                </li>
            </ul>

            <h3 class="m-t-lg text-center ellipsis">GRADIENT CHANGE</h3>
            <ul class="flex flex-main">
                <li class="col-xs-6 col-md-4 col-lg-4 space gradient-area blue-area">
                    <div class="gradient-column gradient-blue-column"></div>
                    <ol class="gradient-block blue-block">
                        <li>Hex 115B8B</li>
                        <li>Hex 1779BA</li>
                        <li>Hex 4594CB</li>
                        <li>Hex 748FD6</li>
                        <li>Hex A2C0E3</li>
                        <li>Hex D1E4F1</li>
                    </ol>
                </li>

                <li class="col-xs-6 col-md-4 col-lg-4 space gradient-area darken-area">
                    <div class="gradient-column gradient-darken-column"></div>
                    <ol class="gradient-block darken-block">
                        <li>Hex 222222</li>
                        <li>Hex 666666</li>
                        <li>Hex 999999</li>
                        <li>Hex CCCCCC</li>
                        <li>Hex DDDDDD</li>
                        <li>Hex EEEEEE</li>
                    </ol>
                </li>

                <li class="col-xs-6 col-md-4 col-lg-4 space gradient-area green-area">
                    <div class="gradient-column gradient-green-column"></div>
                    <ol class="gradient-block green-block">
                        <li>Hex 08b178</li>
                        <li>Hex 16c98d</li>
                        <li>Hex 2fd79e</li>
                        <li>Hex 5be2b5</li>
                        <li>Hex 72edc4</li>
                        <li>Hex a2fdde</li>
                    </ol>
                </li>
            </ul>

        </div>
    </div>
</div>

<?php $this->replace(); ?>

<?php $this->section('footer'); ?>
<?php $this->replace(); ?>
