<?php
$this->layout('layout/layout', [
    'menu' => 'other',
    'selectedMenu' => 'other'
]);
?>

<?php $this->section('main'); ?>

<div class="mains">
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
   
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
    <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quae incidunt, libero inventore minus ipsa repudiandae necessitatibus tempora error beatae sequi commodi explicabo odit optio. Rerum quas nisi deleniti aliquam.
    </div>
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
    <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quae incidunt, libero inventore minus ipsa repudiandae necessitatibus tempora error beatae sequi commodi explicabo odit optio. Rerum quas nisi deleniti aliquam.
    </div>
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
   
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
    <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quae incidunt, libero inventore minus ipsa repudiandae necessitatibus tempora error beatae sequi commodi explicabo odit optio. Rerum quas nisi deleniti aliquam.
    </div>
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
    <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quae incidunt, libero inventore minus ipsa repudiandae necessitatibus tempora error beatae sequi commodi explicabo odit optio. Rerum quas nisi deleniti aliquam.
    </div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
   
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
    <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quae incidunt, libero inventore minus ipsa repudiandae necessitatibus tempora error beatae sequi commodi explicabo odit optio. Rerum quas nisi deleniti aliquam.
    </div>
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fuga nihil consequuntur molestiae odit aspernatur cupiditate nobis quaerat aliquam delectus expedita ducimus in dignissimos, cumque laborum magnam. Nulla molestias ut placeat.
    <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quae incidunt, libero inventore minus ipsa repudiandae necessitatibus tempora error beatae sequi commodi explicabo odit optio. Rerum quas nisi deleniti aliquam.
    </div>
</div>


<?php $this->replace(); ?>

<?php $this->section('footer'); ?>
<?php $this->replace(); ?>
